# 13. Numpy

##  Introduction to Numpy
Numpy is a Library in python that specializes in dealing with multidimensional Arrays. The cool features of Numpy are
* **Automatic Checking :** Numpy ndArrays automatically check the consistancy of data. For instance, it is not possible to have 1st row with 2 elements and 2nd row with 3 elements
* **Contiguous Storage :** Unlike Python Lists, Numpy stores the data in contiguous Memory Locations, leading to lesser Space
* **Faster Vector Arithmatics :** Because of contiguous storage, the operations are performed faster as compared to default Python Execution for Lists

## NumPy Arrays are better than Python List - Comparison

### Advantages of using NumPy Arrays:
#### The most important benefits of using it are :

* It consumes less memory.
* It is fast as compared to the python List.
* It is convenient to use.

In [ ]:
# Installation of Numpy
pip install numpy

In [ ]:
# importing numpy
import numpy

## Check the version

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

### Initialization of 1D array in Python

In [3]:
import numpy as np
array_1D = np.array([2,5,8,1,9])
print(array_1D)

[2 5 8 1 9]


In [114]:
zeros_1D = np.zeros(shape=(1,4))
print(zeros_1D)

[[0. 0. 0. 0.]]


In [119]:
ones_1D = np.ones(shape=(1,4))
print(ones_1D)

[[1. 1. 1. 1.]]


The more important attributes of an ndarray object are

* dtype
* shape
* ndim
* size
* itemsize
* data

**dtype** : Return the type of element in the array

In [4]:
array_1D.dtype

dtype('int32')

**shape** : Return the dimensons of the array

In [9]:
array_1D.shape

(5,)

**ndim** : Return the  number of dimensions of the array

In [83]:
array_1D.ndim

1

**size** : Return the total number of element of the array

In [84]:
array_1D.size

5

**itemsize** : Return the size in bytes of each element of the array

In [85]:
array_1D.itemsize

4

In [94]:
ar1 = np.array([2.1,5.0,8.5,1.5,9.5])
ar1.itemsize

8

In [97]:
ar2 = np.array(["Python","Cpp","Java","C","Sql"])
ar2.itemsize

24

**data**: Return the buffer containing the actual elements of the array

In [86]:
array_1D.data

### Initialization of 2D array in Python

In [88]:
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)


[[1 2 3]
 [4 5 6]]


In [15]:
zeros_2D = np.zeros(shape=(3,5))
print(zeros_2D)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
ones_2D= np.ones(shape=(2,4))
print(ones_2D)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Initialization with Random Values

In [20]:
random1 = np.random.random(size=(2,5))
print(random1)

[[0.15600955 0.377182   0.36627297 0.43269551 0.01306755]
 [0.96500545 0.14176234 0.49933472 0.96852084 0.84864572]]


In [22]:
random2 = np.random.randint(low=0,high=5,size=(3,4))
print(random2)

[[2 0 2 4]
 [2 1 0 3]
 [1 0 3 3]]


In [23]:
random3 = np.random.randn(2,5)
print(random3)

[[-1.31163594 -0.15842753  0.02023803 -0.34400853  0.06502756]
 [-0.07817198  0.39016844 -1.69718076 -0.67449375 -1.68172353]]


## Initialization with arange

In [107]:
# 1 D array
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Using **reshape** we can able to change the dimension of array 

In [108]:
# 2D array
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [120]:
a1=np.arange( 10, 30, 5 )
a1

array([10, 15, 20, 25])

## NumPy Array Slicing
* We pass slice instead of index like this: **[start:end]**.
* We can also define the step, like this: **[start:end:step]**.
* If we don't pass **start** , step = 0
* If we don't pass **end** end = length of array
* If we don't pass **step** step = 1

In [99]:
import numpy as np

arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[::])

[ 1  2  3  4  5  6  7  8  9 10]


## Start

In [38]:
print(arr[2:])

[ 3  4  5  6  7  8  9 10]


## End

In [41]:
print(arr[:8])

[1 2 3 4 5 6 7 8]


In [39]:
print(arr[2:8])

[3 4 5 6 7 8]


## Step

In [42]:
print(arr[::2])

[1 3 5 7 9]


In [44]:
print(arr[:8:2])

[1 3 5 7]


In [40]:
print(arr[2:8:2])

[3 5 7]


## Negative Slicing

In [101]:
print(arr[-6:])

[ 8  9 10]


In [102]:
print(arr[-3:-1])

[8 9]


# Slicing 2-D Arrays 

In [66]:
import numpy as np

#arr1=np.array([index=0, index=1, index=2])
arr1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]])

print(arr1[0, ]) # arr1[element index, slicing index]

[1 2 3 4 5 6 7 8]


In [56]:
print(arr1[0, 1:])

[2 3 4 5 6 7 8]


In [57]:
print(arr1[0, 1:6])

[2 3 4 5 6]


In [58]:
print(arr1[0, 1:6:2])

[2 4 6]


In [59]:
print(arr1[1, ])

[ 9 10 11 12 13 14 15 16]


In [65]:
print(arr1[1, 1:])

[10 11 12 13 14 15 16]


In [64]:
print(arr1[1, 1:6])

[10 11 12 13 14]


In [63]:
print(arr1[1, 1:6:2])

[10 12 14]


In [78]:
print(arr[:1, 1:6])

[[2 3 4 5 6]]


In [79]:
print(arr[:2,1:6])

[[ 2  3  4  5  6]
 [10 11 12 13 14]]


In [80]:
print(arr[:2,1:6:2])

[[ 2  4  6]
 [10 12 14]]


In [81]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [82]:
print(arr2[::2,])

[[ 1  2  3  4]
 [ 9 10 11 12]]


### Arithmetic operation

In [124]:
array_1=np.arange(12).reshape(3,4)
array_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
array_1.sum()

66

In [122]:
array_1.min()

1

In [123]:
array_1.max()

6

In [126]:
# coloum wise
array_1.sum(axis=0) 

array([12, 15, 18, 21])

In [127]:
#row wise
array_1.sum(axis=1)

array([ 6, 22, 38])

In [130]:
array_1.max(axis=0)

array([ 8,  9, 10, 11])

In [131]:
array_1.max(axis=1)

array([ 3,  7, 11])

## Addition

In [147]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[12,11,10],[9,8,7]])
array_3=array_1+array_2
print(array_3)


[[13 13 13]
 [13 13 13]]


## Substract

In [148]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[12,11,10],[9,8,7]])
array_3=array_1-array_2
print(array_3)


[[-11  -9  -7]
 [ -5  -3  -1]]


### Matrix multiplication with Numpy and without Numpy 

In [7]:
# With numpy
import numpy as np 
X = [[1,2],
     [3,4]]  
Y = [[2,1],
     [2,2]]  
# This will return dot product 
res = np.dot(X,Y) 
    
# print resulted matrix 
print(res)

[[ 6  5]
 [14 11]]


In [6]:
# Without numpy

X = [[1,2],
     [3,4]]  
Y = [[2,1],
     [2,2]] 
 
result = [[0,0],
          [0,0]]  

# iterate through rows of X  
for i in range(len(X)):  
   for j in range(len(Y[0])):  
       for k in range(len(Y)):  
           result[i][j] += X[i][k] * Y[k][j]  
for r in result:  
   print(r) 

[6, 5]
[14, 11]


In [9]:
array_1 = np.array([[5,10,15],[20,25,30]])
array_1 = array_1 / 5
print(array_1)

[[1. 2. 3.]
 [4. 5. 6.]]


## Universal Functions
> NumPy provides familiar mathematical functions such as sin, cos, and exp.In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [139]:
array_number=np.arange(6)
array_number

array([0, 1, 2, 3, 4, 5])

###  Exponential function  f(x) = e^x. 

In [140]:
np.exp(array_number)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [141]:
np.sqrt(array_number)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [151]:
np.add(np.arange(1,6), np.arange(7,12))

array([ 8, 10, 12, 14, 16])

## Statistical function

In [179]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Mean

> Mean = (1+2+3+4+5+6+7+8+9) / 9
      = 45 / 9
       = 5

In [181]:
np.mean(arr)

5.0

## Median
* First arrange in ascending order  1, 2, 3, 4, 5, 6, 7, 8, 9
* Find middle number 
* if total numbers in a array is odd then  : middle term is median , median=5
* if total numbers in a array is even then : ((middle term) + (meddle term +1))/2 

In [176]:
np.median(arr)

5.5

## Standard deviation
* The Standard Deviation is a measure of how spread out numbers are
* It is the square root of the Variance

In [173]:
arr.std()

2.8722813232690143

## Linear Algebra Operations 

In [183]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Compute transpose of a matrix

In [184]:
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Create Identity Matrix

In [185]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Trace of a Matrix

In [186]:
print(np.trace(arr))

15


## Compute Determinant of a Matrix

In [189]:
arr=np.array([[1,4],[2,6]])
np.linalg.det(arr)

-2.0